/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiCronRouteImport } from './routes/api/cron'
import { Route as DateDateRouteImport } from './routes/date/$date'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronRoute = ApiCronRouteImport.update({
  id: '/api/cron',
  path: '/api/cron',
  getParentRoute: () => rootRouteImport,
} as any)
const DateDateRoute = DateDateRouteImport.update({
  id: '/date/$date',
  path: '/date/$date',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/cron': typeof ApiCronRoute
  '/date/$date': typeof DateDateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/cron': typeof ApiCronRoute
  '/date/$date': typeof DateDateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/cron': typeof ApiCronRoute
  '/date/$date': typeof DateDateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/cron' | '/date/$date'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/cron' | '/date/$date'
  id: '__root__' | '/' | '/api/cron' | '/date/$date'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiCronRoute: typeof ApiCronRoute
  DateDateRoute: typeof DateDateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron': {
      id: '/api/cron'
      path: '/api/cron'
      fullPath: '/api/cron'
      preLoaderRoute: typeof ApiCronRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/date/$date': {
      id: '/date/$date'
      path: '/date/$date'
      fullPath: '/date/$date'
      preLoaderRoute: typeof DateDateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiCronRoute: ApiCronRoute,
  DateDateRoute: DateDateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
